import type { SidebarConfig } from '@vuepress/theme-default'

const sidebar: SidebarConfig = {
  '/': [
    {
      text: '語言選擇',
      children: [
        '/zh_tw',
        '/ja_jp'
      ]
    }
  ],
  '/zh_tw': [
    {
      text: '裝飾',
      children: [
        '/zh_tw/decor/alien_antenna.md',
        '/zh_tw/decor/angel_circle.md',
        '/zh_tw/decor/cat_ear.md',
        '/zh_tw/decor/cat_hat.md',
        '/zh_tw/decor/christmas_hat.md',
        '/zh_tw/decor/christmas_tree.md',
        '/zh_tw/decor/deer_horn.md',
        '/zh_tw/decor/demon_corner.md',
        '/zh_tw/decor/firework_star.md',
        '/zh_tw/decor/headband_headset.md',
        '/zh_tw/decor/lucky_money.md',
        '/zh_tw/decor/rabbit_ear.md',
        '/zh_tw/decor/witch_hat.md',
      ]
    },
    {
      text: '特性',
      children: [
        '/zh_tw/feature/anniversary.md',
        '/zh_tw/feature/auto_backpack_sort.md',
        '/zh_tw/feature/cat_bowl.md',
        '/zh_tw/feature/cat_day.md',
        '/zh_tw/feature/daily_signin.md',
        '/zh_tw/feature/discord_server.md',
        '/zh_tw/feature/dispenser_industry.md',
        '/zh_tw/feature/drop_limit.md',
        '/zh_tw/feature/edit_sign.md',
        '/zh_tw/feature/enhanced_armor_stand.md',
        '/zh_tw/feature/enhanced_dragon.md',
        '/zh_tw/feature/enhanced_wandering_trader.md',
        '/zh_tw/feature/enhanced_warden.md',
        '/zh_tw/feature/enhanced_wither.md',
        '/zh_tw/feature/entity_glowing.md',
        '/zh_tw/feature/entity_limit.md',
        '/zh_tw/feature/entity_summon.md',
        '/zh_tw/feature/full_map.md',
        '/zh_tw/feature/hopper_limit.md',
        '/zh_tw/feature/invisible_item_frame.md',
        '/zh_tw/feature/item_placement.md',
        '/zh_tw/feature/living_ore.md',
        '/zh_tw/feature/ore_glowing.md',
        '/zh_tw/feature/redstone_limit.md',
        '/zh_tw/feature/removal_mechanism.md',
        '/zh_tw/feature/soul_link.md',
        '/zh_tw/feature/spawn_elder_guardian.md',
      ]
    },
    {
      text: '食物',
      children: [
        '/zh_tw/food/beef_cheese_sandwich.md',
        '/zh_tw/food/beef_jerky.md',
        '/zh_tw/food/candy_cane.md',
        '/zh_tw/food/cheese.md',
        '/zh_tw/food/cheese_puff.md',
        '/zh_tw/food/chocolate.md',
        '/zh_tw/food/chocolate_bone.md',
        '/zh_tw/food/chocolate_bread.md',
        '/zh_tw/food/chocolate_cake.md',
        '/zh_tw/food/chocolate_cookie.md',
        '/zh_tw/food/ice_cream_cone.md',
        '/zh_tw/food/mouldy_bread.md',
      ]
    },
    {
      text: '玩具',
      children: [
        '/zh_tw/item/advanced_tnt.md',
        '/zh_tw/item/axe.md',
        '/zh_tw/item/back.md',
        '/zh_tw/item/barter_menu.md',
        '/zh_tw/item/barter_sell_block.md',
        '/zh_tw/item/boots.md',
        '/zh_tw/item/bow.md',
        '/zh_tw/item/builder_model_device.md',
        '/zh_tw/item/build_blueprint.md',
        '/zh_tw/item/build_replicator_block.md',
        '/zh_tw/item/canned_cat.md',
        '/zh_tw/item/cat_amulet.md',
        '/zh_tw/item/cat_hair.md',
        '/zh_tw/item/cat_hair_brush.md',
        '/zh_tw/item/cat_palm.md',
        '/zh_tw/item/chestplate.md',
        '/zh_tw/item/coin.md',
        '/zh_tw/item/crossbow.md',
        '/zh_tw/item/currency_converter.md',
        '/zh_tw/item/dragon_blood_tooth.md',
        '/zh_tw/item/dragon_hammer.md',
        '/zh_tw/item/dragon_tooth.md',
        '/zh_tw/item/draw_map.md',
        '/zh_tw/item/elytra_of_chestplate.md',
        '/zh_tw/item/ender_dragon_queue.md',
        '/zh_tw/item/energy_laser_crystal.md',
        '/zh_tw/item/entity_exterior_tag.md',
        '/zh_tw/item/exchange_record_gemstone.md',
        '/zh_tw/item/explosive_starlight_water.md',
        '/zh_tw/item/fast_break_magic_wand.md',
        '/zh_tw/item/fast_fill_magic_wand.md',
        '/zh_tw/item/helmet.md',
        '/zh_tw/item/hoe.md',
        '/zh_tw/item/internet_controller.md',
        '/zh_tw/item/invisible_light.md',
        '/zh_tw/item/invite_transfer_gemstone.md',
        '/zh_tw/item/land_block.md',
        '/zh_tw/item/land_book.md',
        '/zh_tw/item/land_energy.md',
        '/zh_tw/item/land_flying_device.md',
        '/zh_tw/item/laser_crystal.md',
        '/zh_tw/item/leggings.md',
        '/zh_tw/item/logger_menu.md',
        '/zh_tw/item/lottery_ticket.md',
        '/zh_tw/item/magic_nether_star.md',
        '/zh_tw/item/music_box.md',
        '/zh_tw/item/newcomer_bag.md',
        '/zh_tw/item/nightmare_crystal.md',
        '/zh_tw/item/notification_block.md',
        '/zh_tw/item/palette.md',
        '/zh_tw/item/particle_block.md',
        '/zh_tw/item/peaceful_block.md',
        '/zh_tw/item/peaceful_proof.md',
        '/zh_tw/item/pen.md',
        '/zh_tw/item/pickaxe.md',
        '/zh_tw/item/piggy_bank.md',
        '/zh_tw/item/pitch_change_pen.md',
        '/zh_tw/item/powerful_ejector_block.md',
        '/zh_tw/item/premium_hopper.md',
        '/zh_tw/item/railway_block.md',
        '/zh_tw/item/random_transfer.md',
        '/zh_tw/item/record_point_banner.md',
        '/zh_tw/item/record_point_gemstone.md',
        '/zh_tw/item/restricted_crafting_table.md',
        '/zh_tw/item/reward_card.md',
        '/zh_tw/item/rope.md',
        '/zh_tw/item/rotten_flesh_block.md',
        '/zh_tw/item/shovel.md',
        '/zh_tw/item/simple_elevator.md',
        '/zh_tw/item/slime_chunk_probe.md',
        '/zh_tw/item/soul_core.md',
        '/zh_tw/item/sound_bell.md',
        '/zh_tw/item/super_fish_cracker.md',
        '/zh_tw/item/sword.md',
        '/zh_tw/item/title_block.md',
        '/zh_tw/item/transfer.md',
        '/zh_tw/item/transfer_book.md',
        '/zh_tw/item/wither_bone_meal.md',
        '/zh_tw/item/world_map_capture.md',
        '/zh_tw/item/world_map_icon.md',
        '/zh_tw/item/world_map_view.md',
      ]
    },
    {
      text: '特殊',
      children: [
        '/zh_tw/special/barrier.md',
        '/zh_tw/special/brown_mushroom.md',
        '/zh_tw/special/cobweb.md',
        '/zh_tw/special/elytra.md',
        '/zh_tw/special/red_mushroom.md',
        '/zh_tw/special/wandering_trader_spawn_egg.md',
      ]
    }
  ]
}

export default sidebar